source "https://rubygems.org"

ruby "~> 3.4.4"

gem "rails", "~> 8.0.1"
gem "sprockets-rails"
gem "dartsass-rails"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "bootsnap", require: false
gem "dotenv-rails"
gem "image_processing", "~> 1.2"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "openapi3_parser"
  gem "factory_bot"
  gem "factory_bot_rails"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rubocop-minitest", require: false
  gem "rubocop-factory_bot", "2.26.1", require: false
  gem "rubocop-rhino-project", "~> 0.25.0.beta.17", require: false
  gem "ffaker"
  gem "simplecov", require: false
  gem "webmock", require: false
end

group :development do
  gem "web-console"
  gem "railroady"
  gem "letter_opener"
end

require "ostruct"

gem "sendgrid-ruby"
gem "sendgrid-actionmailer"
gem "arctic_admin"
gem "activeadmin_addons"
gem "mission_control-jobs", "~> 1.0"
gem "rollbar"
gem "rhino_project", "~> 0.25.0.beta.17"
gem "rhino_project_core", "~> 0.25.0.beta.17"
gem "rhino_project_organizations", "~> 0.25.0.beta.17"
gem "rhino_project_notifications", "~> 0.25.0.beta.17"
gem "rhino_project_subscriptions", "~> 0.25.0.beta.17"
gem "vite_rails", "~> 3.0"