source "https://rubygems.org"

ruby "3.4.1"

gem "rails", "~> 8.0"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false
gem "discard", "~> 1.4"
gem "request_store", "~> 1.7"
gem "pundit"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "rspec-rails"
end

group :test do
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers"
end