/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Organization: {
            id?: number;
            /** Format: date-time */
            created_at?: string;
            description?: string | null;
            is_active?: boolean | null;
            name?: string;
            slug?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Role: {
            id?: number;
            /** Format: date-time */
            created_at?: string;
            description?: string | null;
            name?: string;
            slug?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Project: {
            id?: number;
            budget?: number | null;
            /** Format: date-time */
            created_at?: string;
            description?: string | null;
            /** Format: date-time */
            discarded_at?: string | null;
            /** Format: date-time */
            ends_at?: string | null;
            internal_notes?: string | null;
            organization_id?: number;
            /** Format: date-time */
            starts_at?: string | null;
            status?: string;
            title?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Task: {
            id?: number;
            assignee_id?: number | null;
            /** Format: date-time */
            created_at?: string;
            description?: string | null;
            /** Format: date-time */
            discarded_at?: string | null;
            /** Format: date-time */
            due_date?: string | null;
            estimated_hours?: number | null;
            priority?: string;
            project_id?: number;
            status?: string;
            title?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Comment: {
            id?: number;
            body?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            discarded_at?: string | null;
            task_id?: number;
            /** Format: date-time */
            updated_at?: string;
            user_id?: number;
            uuid?: string | null;
        };
        Label: {
            id?: number;
            color?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            discarded_at?: string | null;
            name?: string;
            organization_id?: number;
            /** Format: date-time */
            updated_at?: string;
        };
        Blog: {
            id?: number;
            organization_id?: number;
            title?: string | null;
            body?: string | null;
            published?: boolean | null;
            /** Format: date-time */
            discarded_at?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
